export enum ProductType {
  LAPTOP = "LAPTOP",
  SMARTPHONE = "SMARTPHONE",
  TELEVISION = "TELEVISION",
  FURNITURE = "FURNITURE",
  CAMERA = "CAMERA",
  CLOTHING = "CLOTHING",
  BOOK = "BOOK",
  SPORTS_EQUIPMENT = "SPORTS_EQUIPMENT",
  TOY = "TOY",
  JEWELRY = "JEWELRY",
  ART_SUPPLIES = "ART_SUPPLIES",
  AUTOMOTIVE_PART = "AUTOMOTIVE_PART",
  MUSICAL_INSTRUMENT = "MUSICAL_INSTRUMENT",
  OFFICE_EQUIPMENT = "OFFICE_EQUIPMENT"
  }